#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# The production DATABASE_URL ends up in here. Already gitignored; the wizard
# refuses to run if that ever stops being true.
ENV_FILE=".env.production.local"

BRANCH="claude/arkitech-simplified"
REPO_SLUG="WaltLuv/arkitech-ai"

banner "Arkitech AI: Neon + Render deployment"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking this machine can do the parts that are not browser work."

if [[ ! -f render.yaml || ! -d drizzle ]]; then
  warn "Run this from the root of the Arkitech repository."
  exit 1
fi
say "Repository root: ok"

if ! git check-ignore -q "$ENV_FILE"; then
  warn "$ENV_FILE is not gitignored. Stopping rather than risk committing a"
  warn "production database URL. Add it to .gitignore and re-run."
  exit 1
fi
say "$ENV_FILE is gitignored: ok"

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ "$CURRENT_BRANCH" != "$BRANCH" ]]; then
  warn "You are on '$CURRENT_BRANCH', and the production candidate is '$BRANCH'."
  confirm "Continue anyway?" || exit 1
fi
say "Branch: $CURRENT_BRANCH"
say "Commit: $(git rev-parse --short HEAD)"

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "GitHub CLI: authenticated"
else
  warn "GitHub CLI is missing or not logged in."
  note "Install it from https://cli.github.com, then run: gh auth login"
  note "Stages 3 and 4 need it. You can still do the rest by hand."
  confirm "Continue without it?" || exit 1
fi

pause "Press Enter to start."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Neon: create the production database"
say "Arkitech needs two forms of the same Neon connection string."
note "Pooled, for the app: PgBouncer, handles many short-lived connections."
note "Direct, for migrations: DDL is unreliable through a transaction pooler."
open_url "https://console.neon.tech/signup"
step "Sign up or log in."
step "Create a project. Name it 'arkitech-production'."
step "Pick the region closest to Oregon (us-west-2) to sit near Render."
step "Once created, open the project's Connection Details panel."
pause "Press Enter when the project exists."

say ""
say "First the pooled string, which Render will use."
step "In Connection Details, make sure 'Pooled connection' is ON."
step "Copy the whole postgresql://... string."
ask_secret NEON_POOLED_URL "Paste the POOLED connection string:"

if [[ "$NEON_POOLED_URL" != *"-pooler."* ]]; then
  warn "That string has no '-pooler' in its host, so it is probably the direct"
  warn "one. Re-check the 'Pooled connection' toggle if the app misbehaves."
fi

say ""
say "Now the direct string, which the migration workflow will use."
step "Turn 'Pooled connection' OFF. The host loses its '-pooler' suffix."
step "Copy that string too."
ask_secret NEON_DIRECT_URL "Paste the DIRECT connection string:"

if [[ "$NEON_DIRECT_URL" == *"-pooler."* ]]; then
  warn "That one still has '-pooler' in the host. Migrations may fail."
  confirm "Use it anyway?" || exit 1
fi

write_env DATABASE_URL "$NEON_POOLED_URL"
write_env DATABASE_URL_DIRECT "$NEON_DIRECT_URL"
say ""
note "Both are in $ENV_FILE, which git ignores. Never commit it."
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "GitHub: the production environment secret"
say "The migration workflow reads DATABASE_URL from a GitHub Environment"
say "named 'production', not from a plain repository secret. That is what"
say "lets you require a reviewer before anything touches the database."

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if printf '%s' "$NEON_DIRECT_URL" | gh secret set DATABASE_URL \
      --env production --repo "$REPO_SLUG" >/dev/null 2>&1; then
    printf '  %s✓ set%s DATABASE_URL on the production environment\n' "$GREEN" "$RESET"
    WRITTEN_SECRET+=("DATABASE_URL (production environment)")
  else
    warn "Could not set it. The environment may not exist yet."
    open_url "https://github.com/$REPO_SLUG/settings/environments"
    step "Click 'New environment', name it exactly: production"
    step "Optionally add yourself as a required reviewer."
    step "Under 'Environment secrets', add DATABASE_URL with the DIRECT string."
    SKIPPED+=("DATABASE_URL on the production environment")
    pause "Press Enter when it is set."
  fi
else
  open_url "https://github.com/$REPO_SLUG/settings/environments"
  step "Click 'New environment', name it exactly: production"
  step "Under 'Environment secrets', add DATABASE_URL with the DIRECT string."
  SKIPPED+=("DATABASE_URL on the production environment")
  pause "Press Enter when it is set."
fi

say ""
say "Make sure the branch carrying the workflow is pushed."
if confirm "Push $BRANCH to origin now?"; then
  git push -u origin "$BRANCH" || warn "Push failed; push it by hand before stage 4."
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Run the migrations"
say "Two passes. The dry run connects and counts tables without writing."
say "Only the second one applies anything."
say ""
note "All 12 migrations are additive and idempotent, so applying them to a"
note "database that already has them is a no-op rather than an error."

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say ""
  if confirm "Start the DRY RUN now?"; then
    gh workflow run production-migrations.yml --repo "$REPO_SLUG" \
      --ref "$BRANCH" -f mode=dry-run -f reason="Wizard dry run" \
      && say "Started. Watch it below." \
      || warn "Could not start it; use the Actions tab."
  fi
  open_url "https://github.com/$REPO_SLUG/actions/workflows/production-migrations.yml"
  pause "Press Enter once the dry run is green."

  say ""
  warn "The next run writes to the production database."
  if confirm "Apply the migrations now?"; then
    gh workflow run production-migrations.yml --repo "$REPO_SLUG" \
      --ref "$BRANCH" -f mode=apply -f reason="Wizard apply" \
      && say "Started." \
      || warn "Could not start it; use the Actions tab."
    pause "Press Enter once it is green."
  else
    SKIPPED+=("Applying migrations (run the workflow with mode=apply)")
  fi
else
  open_url "https://github.com/$REPO_SLUG/actions/workflows/production-migrations.yml"
  step "Click 'Run workflow'."
  step "Choose branch: $BRANCH"
  step "Choose mode: dry-run. Run it, and wait for green."
  step "Run it again with mode: apply."
  pause "Press Enter once the apply run is green."
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Render: create the service from the blueprint"
say "render.yaml in this repo describes the whole service, so Render reads it"
say "rather than you filling in a form."
open_url "https://dashboard.render.com/register"
step "Sign up or log in, then connect your GitHub account."
step "Grant Render access to the $REPO_SLUG repository."
say ""
open_url "https://dashboard.render.com/blueprints"
step "Click 'New Blueprint Instance'."
step "Pick the $REPO_SLUG repository."
warn "Set the branch to: $BRANCH"
warn "NOT main. main has no health endpoint, so the service never goes live."
step "Render reads render.yaml and shows the service 'arkitech-ai'."
step "Do NOT deploy yet. It has no secrets, so the first build would fail."
pause "Press Enter once the blueprint is created."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Render: the 15 secrets"
say "Every secret in render.yaml is 'sync: false', so none of them is in git."
say "You set each one in the dashboard now."
open_url "https://dashboard.render.com"
step "Open the arkitech-ai service → Environment."
say ""
say "Set these 15, exactly by name:"
note "  DATABASE_URL                       the POOLED Neon string"
note "  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY  Clerk → API keys"
note "  CLERK_SECRET_KEY                   Clerk → API keys"
note "  NEXT_PUBLIC_APP_URL                leave for stage 7"
note "  GOOGLE_CLOUD_GEMINI_API_KEY        Google AI Studio"
note "  OPENAI_API_KEY                     OpenAI dashboard"
note "  COMPOSIO_API_KEY                   Composio dashboard"
note "  BROWSERBASE_API_KEY                Browserbase settings"
note "  BROWSERBASE_PROJECT_ID             Browserbase settings"
note "  INNGEST_EVENT_KEY                  Inngest → Event keys"
note "  INNGEST_SIGNING_KEY                Inngest → Signing key"
note "  CHANNEL_SECRET_KEY                 generate: openssl rand -base64 32"
note "  SLACK_CLIENT_ID                    Slack app → Basic Information"
note "  SLACK_CLIENT_SECRET                Slack app → Basic Information"
note "  SLACK_SIGNING_SECRET               Slack app → Basic Information"
say ""
say "Your pooled Neon string is the DATABASE_URL value, saved in $ENV_FILE."
warn "Rotating CHANNEL_SECRET_KEY later orphans every Telegram and Slack"
warn "connection customers have made. Generate it once and keep it."
say ""
note "The optional ones keep their defaults unless you set them:"
note "  OPENAI_MODEL, OPENAI_COMPUTER_MODEL, BROWSER_SLOT_LIMIT,"
note "  BROWSER_MAX_*, BROWSERBASE_AGENT_ID"
pause "Press Enter once all 15 are set."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Render: first deploy, then its own URL"
say "NEXT_PUBLIC_APP_URL is the awkward one: its value is the address Render"
say "assigns, which does not exist until the service is created. So it gets"
say "set after the first deploy, and the service is redeployed."
step "Click 'Manual Deploy' → 'Deploy latest commit'."
step "Watch the build. It ends with a health check against /api/health."
pause "Press Enter once the deploy finishes."
say ""
step "Copy the service URL from the top of the Render page."
note "It looks like https://arkitech-ai.onrender.com"
ask ARKITECH_URL "Paste the production URL:"

ARKITECH_URL="${ARKITECH_URL%/}"

if [[ "$ARKITECH_URL" != https://* ]]; then
  warn "That is not an https:// URL. Telegram refuses anything else, and the"
  warn "connect route will reject it."
  confirm "Use it anyway?" || exit 1
fi

write_env NEXT_PUBLIC_APP_URL "$ARKITECH_URL"
say ""
step "Back in Render → Environment, set NEXT_PUBLIC_APP_URL to that URL."
step "Save. Render redeploys automatically."
warn "Until this redeploy finishes, Telegram and Slack connections refuse."
pause "Press Enter once the redeploy is done."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Verify the deployment"
say "The health endpoint is public and returns states only, so this is safe"
say "to call from anywhere."
say ""
if command -v curl >/dev/null 2>&1; then
  say "GET $ARKITECH_URL/api/health"
  say ""
  curl -s -m 20 "$ARKITECH_URL/api/health" || warn "Request failed."
  say ""
  say ""
  note 'Healthy looks like: {"status":"ok","database":"ok",...}'
  note '"database":"unreachable" means the pooled DATABASE_URL is wrong.'
  note '"browserExecution":"not_configured" means the Browserbase keys are unset.'
else
  open_url "$ARKITECH_URL/api/health"
fi
say ""
step "Open the app and sign in, to check Clerk is configured."
open_url "$ARKITECH_URL"
pause "Press Enter when you have signed in."
say ""
say "Then confirm by hand, in the app:"
note "  - Agents 1, 2 and 3 can be created; a 4th is refused"
note "  - the Usage Credit balance shows"
note "  - a Run charges credits"
note "  - a Browserbase task starts, Watch shows it, control hands over and back"
note "  - Stop closes the session, and activity persists after a reload"
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Channels: point the providers at production"
say "Both providers need the real URL, which only existed from stage 7."
say ""
say "Slack:"
open_url "https://api.slack.com/apps"
step "Open your Arkitech app → OAuth & Permissions."
step "Add this Redirect URL:"
note "  $ARKITECH_URL/api/channels/slack/callback"
step "Event Subscriptions → Request URL:"
note "  $ARKITECH_URL/api/channels/slack/events"
step "Save, and reinstall the app to your workspace if Slack asks."
pause "Press Enter when Slack is saved."
say ""
say "Telegram needs nothing configured here: each customer brings their own"
say "bot token through the Connections screen, and Arkitech registers the"
say "webhook itself against NEXT_PUBLIC_APP_URL."
say ""
step "In Arkitech, connect a Telegram bot and send it a message."
step "Then connect Slack through the Connections screen and message the bot."
note "Neither channel is verified until a real message round-trips."
pause

finish

printf '  %sProduction URL:%s %s\n' "$BOLD" "$RESET" "${ARKITECH_URL:-not captured}"
printf '  %sBranch:%s         %s\n' "$BOLD" "$RESET" "$BRANCH"
printf '  %sHealth check:%s   %s/api/health\n\n' "$BOLD" "$RESET" "${ARKITECH_URL:-...}"
note "Re-run this wizard any time; it offers saved values as defaults."
printf '\n'
